# docker-compose 多容器部署
# 启动命令 docker compose up --detach 后台启动
version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest-practice
    volumes:
      - .volumes/db:/var/lib/mysql

  # 网页版数据库管理工具phpmyadmin(http://localhost:8080), 推荐使用 navicat
  phpmyadmin:
    container_name: mysql-phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80

  # ElasticSearch 集群
  es01:
    image: elasticsearch:8.6.1 # image: docker.elastic.co/elasticsearch/elasticsearch:8.6.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - .volumes/es01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  es02:
    image: elasticsearch:8.6.1 # image: docker.elastic.co/elasticsearch/elasticsearch:8.6.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - .volumes/es02:/usr/share/elasticsearch/data
  kibana:
    image: kibana:8.6.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - SERVERNAME=kibana
      - I18N_LOCALE=zh-CN
      - ELASTICSEARCH_HOSTS=http://es01:9200
    depends_on:
        - es01
    volumes:
      - .volumes/kibana:/usr/share/kibana/data

