# docker-compose 多容器部署
# 启动命令 docker compose up --detach 后台启动
version: '3.1'

services:

  db:
    image: mysql
    container_name: nest-practice
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/docker/volumes/mysql_data

  # 网页版数据库管理工具(http://localhost:8080), 推荐使用 navicat
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db:
    driver: local
