db_config:
  type: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "root"
  database: "nest-practice"
#  logging: true # ['error']
  logging:  ['error']
  synchronize: true # 启动数据库时自动根据加载的模型(Entity)来同步数据表到数据库
  autoLoadEntities: true # 这样我们就不需要把每个模块的Entity逐个定死地添加到配置中的entities数组中了，因为你可以在每个模块中使用TypeOrmModule.forFeature来动态的加入Entity

elastic_config:
  node: 'http://localhost:9200'
  username: "elastic"
  password: "elastic"

app_config:
  searchType: "elastic" # 全文搜索: like, against, elastic
  jwtSecret: '123456'
  jwtExpiresIn: '1 day'
